"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:color_green bg:default)\
$directory\
[](fg:color_green bg:color_yellow)\
$git_branch\
$git_status\
[](fg:color_yellow bg:color_pink)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_pink bg:color_purple)\
$docker_context\
$kubernetes\
$aws\
[](fg:color_purple bg:color_bg1)\
$shell\
$shlvl\
$time\
[ ](fg:color_bg1 bg:default)\
$fill\
$cmd_duration\
$line_break$character"""

continuation_prompt = '[󰄾 ](fg:color_green) '
palette = 'monokai_pro_spectrum'

[palettes.monokai_pro_spectrum]
color_aqua = '#6ab0f3'
color_bg0 = '#222222'
color_bg1 = '#69676c'
color_blue = '#5ad4e6'
color_green = '#7bd88f'
color_orange = '#fc9867'
color_pink = '#fc618d'
color_purple = '#948ae3'
color_yellow = '#fce566'
color_white = '#f7f1ff'

[directory]
truncate_to_repo = true
truncation_length = 3
before_repo_root_style = "fg:color_bg0 bg:color_green"
repo_root_style = "bold fg:color_bg0 bg:color_green"
style = "fg:color_bg0 bg:color_green"
read_only_style = "fg:color_bg0 bg:color_green"
format = "[ $path ]($style)"
repo_root_format = '[$before_root_path]($before_repo_root_style)[󰊢$repo_root]($repo_root_style)[$path ]($style)[$read_only]($read_only_style)'
home_symbol = ""
fish_style_pwd_dir_length=2

[git_branch]
symbol = ""
# style = "bg:color_yellow"
format = '[[ $symbol $branch ](fg:color_bg0 bg:color_yellow)]($style)'

[git_status]
# style = "bg:color_yellow"
format = '[[($all_status$ahead_behind )](fg:color_bg0 bg:color_yellow)]($style)'

[nodejs]
detect_extensions = []
symbol = ""
# style = "bg:color_pink"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_pink)]($style)'

[c]
symbol = " "
# style = "bg:color_pink"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_pink)]($style)'

[rust]
symbol = ""
# style = "bg:color_pink"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_pink)]($style)'

[golang]
symbol = ""
# style = "bg:color_pink"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_pink)]($style)'

[php]
symbol = ""
# style = "bg:color_pink"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_pink)]($style)'

[java]
symbol = " "
# style = "bg:color_pink"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_pink)]($style)'

[kotlin]
symbol = ""
# style = "bg:color_pink"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_pink)]($style)'

[haskell]
symbol = ""
# style = "bg:color_pink"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_pink)]($style)'

[python]
pyenv_version_name = true
detect_extensions = []
symbol = ""
# style = "bg:color_pink"
format = '[[ $symbol( $version) ](fg:color_bg0 bg:color_pink)]($style)'

[docker_context]
symbol = " "
style = "bg:color_purple"
format = '[[ $symbol( $context) ](fg:color_blue bg:color_purple)]($style)'

[kubernetes]
format = '[[ $symbol $cluster $context \($namespace\)](fg:color_blue bg:color_purple)]($style)'
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
]

[aws]
symbol = " "
style = 'bold orange'
format = '[[ $symbol$profile](fg:color_white bg:color_purple)]($style)'
[aws.profile_aliases]
Enterprise_Naming_Scheme-voidstars = 'void**'

[shell]
disabled = true
format = "[[ $indicator](fg:color_white bg:color_bg1)]($style)"

[shlvl]
disabled = false
style = "bg:color_bg1"
format = "[[ zsh:$shlvl](fg:color_white bg:color_bg1)]($style)"
threshold = 2

[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:color_bg1"
format = '[[ $time](bold fg:color_white bg:color_bg1)]($style)'

[fill]
disabled = false
symbol = " "

[cmd_duration]
min_time = 1000
format = '[$duration](bold color_yellow)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_pink)'
vimcmd_symbol = '[](bold fg:color_yellow)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_green)'
