#!/bin/sh
set -eu
if [ "${DEBUG:=}" = true ]; then set -x; fi

cd "${HOME}/code/github.com"

FILES=$(
    find "cddc39" "dmikalova" "e91e63" "screeptorio" \( \
        -type d -name ".terragrunt-cache" -o \
        -type d -name "node_modules" \
        \) -prune -o \( \
        -name "main.tf" -o \
        -type d -name ".git" -o \
        -name "README.md" \
        \) -print
)

for FILE in $FILES; do
    DIR=$(dirname "${FILE}")
    README="${DIR}/README.md"
    # test if exists
    echo "$(tput setaf 1)${README}$(tput sgr0)"
    if ! test -f "${README}"; then
        code "${README}"
        exit
    fi
    # test if empty
    if ! test -s "${README}"; then
        code "${README}"
        exit
    fi
    head "${README}"
done
